// <auto-generated />
using System;
using CostcoReceipts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostcoReceipts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528222615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.PlaceholderUser", b =>
                {
                    b.Property<string>("PlaceholderId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ReceiptId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("PlaceholderId", "ReceiptId");

                    b.ToTable("placeholder_users", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.Receipt", b =>
                {
                    b.Property<string>("ReceiptId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptGeometry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("BoundingBoxHeight")
                        .HasColumnType("double");

                    b.Property<double>("BoundingBoxLeft")
                        .HasColumnType("double");

                    b.Property<double>("BoundingBoxTop")
                        .HasColumnType("double");

                    b.Property<double>("BoundingBoxWidth")
                        .HasColumnType("double");

                    b.Property<double>("Confidence")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId", "FieldName", "FieldType")
                        .IsUnique();

                    b.ToTable("receipt_geometry", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ItemNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId", "ItemIndex")
                        .IsUnique();

                    b.ToTable("receipt_items", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptItemAssignment", b =>
                {
                    b.Property<long>("ReceiptItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("ReceiptItemId", "UserId");

                    b.ToTable("receipt_item_assignments", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Comments")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PlaceholderId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ReceiptId", "UserId")
                        .IsUnique();

                    b.ToTable("receipt_members", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("receipt_shares", (string)null);
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptGeometry", b =>
                {
                    b.HasOne("CostcoReceipts.Api.Data.Entities.Receipt", "Receipt")
                        .WithMany("Geometry")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptItem", b =>
                {
                    b.HasOne("CostcoReceipts.Api.Data.Entities.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptItemAssignment", b =>
                {
                    b.HasOne("CostcoReceipts.Api.Data.Entities.ReceiptItem", "ReceiptItem")
                        .WithMany("Assignments")
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiptItem");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptMember", b =>
                {
                    b.HasOne("CostcoReceipts.Api.Data.Entities.Receipt", "Receipt")
                        .WithMany("Members")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptShare", b =>
                {
                    b.HasOne("CostcoReceipts.Api.Data.Entities.Receipt", "Receipt")
                        .WithMany("Shares")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.Receipt", b =>
                {
                    b.Navigation("Geometry");

                    b.Navigation("Items");

                    b.Navigation("Members");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CostcoReceipts.Api.Data.Entities.ReceiptItem", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
